### PR TITLE
Fix mention prefix due to mismatch between different mentions. Fixes #212

### LINKED ISSUE #212: [Bug] Mentioning cascade doesn't show prefix
**Describe the bug**
mentioning cascade doesnt show prefix

**To Reproduce**
1. mention cascade

**Expected behavior**
show prefix

### PR DESCRIPTION
**Pull request by weeryan17**
# Pull request

 - [x] I have read and agreed to the [code of conduct](https://github.com/CascadeBot/CascadeBot/blob/master/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/CascadeBot/CascadeBot/blob/master/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me or was not being worked on and is a somewhat requested feature. For reference see our [GitHub projects](https://github.com/orgs/CascadeBot/projects).
 - [x] I have tested all of my changes.
 
## Added/Changed
Fixed mention prefix due to having a mismatch between the two different ways of mentioning users

## Feature
N/A

### CODE REVIEW

File: src/main/java/org/cascadebot/cascadebot/events/CommandListener.java [hunk 1]
```diff
@@ -81,10 +82,17 @@ public void onGuildMessageReceived(GuildMessageReceivedEvent event) {
         String trigger;
         String[] args;
 
+        boolean messagesBot = false;
+        for (Member member : event.getMessage().getMentionedMembers()) {
+            if (member.getIdLong() == event.getGuild().getSelfMember().getIdLong()) {
+                messagesBot = true;
+            }
+        }
+
```
Comment (binaryoverload) [inline src/main/java/org/cascadebot/cascadebot/events/CommandListener.java:91]: This won't work as intended as you could mention the bot at any point in the message.

We need to do what we did but just use maybe regex for it to match the extra character.

File: src/main/java/org/cascadebot/cascadebot/events/CommandListener.java [hunk 2]
```diff
@@ -81,10 +82,17 @@ public void onGuildMessageReceived(GuildMessageReceivedEvent event) {
...
         if (message.startsWith(prefix)) {
             commandWithArgs = message.substring(prefix.length()); // Remove prefix from command
-        } else if (guildData.getCoreSettings().isMentionPrefix() && message.startsWith(event.getJDA().getSelfUser().getAsMention())) {
-            commandWithArgs = message.substring(event.getJDA().getSelfUser().getAsMention().length()).trim();
+        } else if (guildData.getCoreSettings().isMentionPrefix() && messagesBot) {
+            commandWithArgs = message.substring(event.getJDA().getSelfUser().getAsMention().length() + 1).trim();
```
Comment (binaryoverload) [inline src/main/java/org/cascadebot/cascadebot/events/CommandListener.java:95]: I'm *pretty* sure that if we use context.getMember().getAsMention() this will work as before.

File: src/main/java/org/cascadebot/cascadebot/events/CommandListener.java [hunk 3]
```diff
@@ -77,18 +80,32 @@ public void onGuildMessageReceived(GuildMessageReceivedEvent event) {
...
         String trigger;
         String[] args;
 
+        // Check that the bot is even mentioned in the first place
+        boolean messagesBot = false;
+        for (Member member : event.getMessage().getMentionedMembers()) {
+            if (member.getIdLong() == event.getGuild().getSelfMember().getIdLong()) {
+                messagesBot = true;
+            }
+        }
```
[the remark this answers is not in the document]
Comment (weeryan17) [reply src/main/java/org/cascadebot/cascadebot/events/CommandListener.java:93]: I figured we want to check if the bot is mentioned at all before we check if its at the begining, yes it isn't needed as much with the regex, but still cuts out having to run the checking at start logic.
