### PR TITLE
Fixed ;userinfo bug

### LINKED ISSUE #126: [Bug] Userinfo does not return right
**Describe the bug**
Whenever you try to get information on valid user bot cannot see, it does not return invid user embed

**To Reproduce**
1. Type ;userinfo `ID from someone bot cannot see`

**Expected behavior**
- Catched error and clear embed telling that the user is invalid
> Instead, it posts a stacktrace on hastebin

**Screenshots**
_nothing_

**Additional context**
Add any other context about the problem here such as what device for visual bugs.
_nothing_

### PR DESCRIPTION
**Pull request by JamesHawkinss**
# Pull request

 - [x] I have read and agreed to the [code of conduct](https://github.com/CascadeBot/CascadeBot/blob/master/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/CascadeBot/CascadeBot/blob/master/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me or was not being worked on and is a somewhat requested feature. For reference see our [GitHub projects](https://github.com/orgs/CascadeBot/projects).
 - [x] I have tested all of my changes.
 
## Added/Changed
Fixed userinfo bug, reported by DeadlyFire.

Closes #126

### CODE REVIEW

File: src/main/java/org/cascadebot/cascadebot/commands/informational/UserInfoCommand.java [hunk 1]
```diff
@@ -38,17 +39,21 @@ public void onCommand(Member sender, CommandContext context) {
         User userForInfo = sender.getUser();
         if (userArg.argExists(context.getArgs(), 0)) {
             userForInfo = DiscordUtils.getUser(context.getGuild(), context.getMessage(0), true);
+            // userForInfo = CascadeBot.INS.getShardManager().getUserById(context.getMessage(0));
```
Comment (binaryoverload) [inline src/main/java/org/cascadebot/cascadebot/commands/informational/UserInfoCommand.java]: Remove this

File: src/main/java/org/cascadebot/cascadebot/commands/informational/UserInfoCommand.java [hunk 2]
```diff
@@ -38,17 +39,21 @@ public void onCommand(Member sender, CommandContext context) {
...
         if (userForInfo == null) {
-            context.getTypedMessaging().replyDanger("Invalid User!");
+            context.getTypedMessaging().replyDanger("We couldn't find that user!");
             return;
         }
         Member member = context.getGuild().getMember(userForInfo);
 
         String status = "";
         String statusName = "";
+        List<Page> pageList = new ArrayList<>();
```
Comment (binaryoverload) [inline src/main/java/org/cascadebot/cascadebot/commands/informational/UserInfoCommand.java]: pageList can stay where it was, we don't need it for this
